### ISSUE TITLE
Issue with Slack API Token for Acceptance Tests

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-slack#35]
On running acceptance tests for the provider with the new version of the slack tf provider, we not get this error

```
    slack:index:Conversation (acc-test):
      error: 1 error occurred:
      	* api user could not join conversation: missing_scope
```

I can't find any details on how to regenerate a new API Token for the provider

**Comment by jkisk** [comment]
I'll take care of it, for future reference details are in our password manager.
